# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
workspace 'Eventful'
target 'Eventful' do
    project '/Users/BandManFabo/Desktop/EventfulApp/EventfulApp1/Eventful/Eventful.xcodeproj'
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    workspace 'Eventful'
    use_frameworks!
    pod 'Firebase/Core'
    pod 'Firebase/Auth’
    pod 'Firebase/Database’
    pod 'Firebase/Storage’
    pod 'Firebase/Messaging’
    pod 'BPStatusBarAlert'
    pod ’SwiftyJSON’
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'AlamofireNetworkActivityIndicator'
    pod ‘SVProgressHUD’
    pod 'SwiftyCam', :git => 'https://github.com/Awalz/SwiftyCam.git', :branch => 'Swift4'
    pod ‘TextFieldEffects’
    pod 'SwiftLocation'
    pod 'IGListKit', :git => 'https://github.com/Instagram/IGListKit.git', :branch => 'master'
    pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'FaceAware'
    pod 'NotificationBannerSwift'
    pod 'GooglePlaces'
    pod 'GooglePlacePicker'
    pod 'GoogleMaps'
    pod 'JTAppleCalendar'
    pod 'RevealingSplashView'
    pod "RecordButton"
    # Pods for Eventful
    
end
