# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
workspace 'Eventful'
target 'Eventful' do
    #project '/Users/BandManFabo/Desktop/EventfulApp/EventfulApp1/Eventful/Eventful.xcodeproj'
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    workspace 'Eventful'
    use_frameworks!
    pod 'Firebase/Core'
    pod 'Firebase/Auth’
    pod 'Firebase/Database’
    pod 'Firebase/Storage’
    pod 'Firebase/Messaging’
    pod 'BPStatusBarAlert'
    pod 'Alamofire'
    pod 'AlamofireImage'
    pod 'AlamofireNetworkActivityIndicator'
    pod ‘SVProgressHUD’
    pod 'SwiftLocation'
    pod 'IGListKit', :git => 'https://github.com/Instagram/IGListKit.git', :branch => 'master'
    pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git'
    pod 'Fabric'
    pod 'Crashlytics'
    
    pod 'NotificationBannerSwift', '1.6.3'
    pod 'MarqueeLabel/Swift', '3.1.6'
    pod 'GooglePlaces'
    pod 'GooglePlacePicker'
    pod 'GoogleMaps'
    pod 'JTAppleCalendar', :git => 'https://github.com/patchthecode/JTAppleCalendar.git', :branch => 'master'
    pod 'RevealingSplashView'
    pod "RecordButton"
    pod 'DTPagerController'
    pod 'SimpleImageViewer', '~> 1.1.1'
    pod 'IQKeyboardManagerSwift'
    pod 'SwipeCellKit',:git => 'https://github.com/SwipeCellKit/SwipeCellKit.git', :branch => 'master'
    pod 'XLActionController/Twitter'
    pod 'Instabug'
    pod 'InstantSearch'
    pod 'YNSearch'
    pod 'AMPopTip'
    
    pod 'AZDialogView'
    pod 'Eureka'
    pod 'ImageRow', '~> 3.0'
    pod 'AlgoliaSearch-Client-Swift'
    pod 'Kingfisher'
    pod 'DZNEmptyDataSet'
    pod 'Segmentio', :git => 'https://github.com/Yalantis/Segmentio', :branch => 'master'
    pod 'TransitionButton'

    pod 'AFDateHelper'
    pod 'ColorSlider'
    pod 'SnapSliderFilters'
    
    pod 'YPImagePicker'
    pod 'OneSignal', '>= 2.6.2', '< 3.0'
    pod 'SnapKit', '~> 4.0.0'

    pod 'Parchment',:git => 'https://github.com/rechsteiner/Parchment', :branch => 'master'
    pod 'TagListView', '~> 1.0'

    pod "SkeletonView"
    pod 'SideMenuSwift'
    
    # Pods for Eventful
end


target 'OneSignalNotificationServiceExtension' do
    use_frameworks!
    pod 'OneSignal', '>= 2.6.2', '< 3.0'
end
